Feature/coloring road
p0l0satik/SphericalProjectionDataloader pull request #1
Opened 2023-09-06 12:39 UTC by p0l0satik

added road labels from kitti

2023-09-11 18:01 UTC, kirill-ivanov-a requested changes

2023-09-14 14:33 UTC, p0l0satik commented on loader/dataloader.py
> +    def __init__(self, dir, len) -> None:
fixed

2023-09-14 14:33 UTC, p0l0satik commented on loader/dataloader.py
> +        self.label_folder = dir + "plane_labels/"
fixed

2023-09-14 14:34 UTC, p0l0satik commented on loader/dataloader.py
> +        KITI_ROAD_LABELS = (40, 48, 44, 49)
fixed

2023-09-14 14:34 UTC, p0l0satik commented on loader/laserscan.py
> +from torch import int16
fixed

2023-09-14 14:34 UTC, p0l0satik commented on loader/dataloader.py
> +        self.ls.open_scan(self.file_folder + '{0:06d}.bin'.format(idx))
fixed

2023-09-14 14:34 UTC, p0l0satik commented on loader/laserscan.py
> +  def __init__(self,  H=64, W=1024, fov_up=3.0, fov_down=-25.0):
fixed

2023-09-14 14:34 UTC, p0l0satik commented on loader/laserscan.py
> +  def open_scan(self, filename):
fixed

2023-09-14 14:34 UTC, p0l0satik commented on loader/laserscan.py
> +    else:
fixed

2023-09-14 14:34 UTC, p0l0satik commented on loader/laserscan.py
> +    proj_y = np.minimum(self.proj_H - 1, proj_y)
fixed

2023-09-14 14:37 UTC, p0l0satik commented on loader/laserscan.py
> +      sem_label = label & 0xFFFF  # semantic label in lower half
Arguably, but I insist on leaving bit masks and shifts as is because they are commented

2023-09-14 14:37 UTC, p0l0satik commented on visualisation.py
> +
fixed

2023-09-14 14:38 UTC, p0l0satik commented on visualisation.py
> +def visualise(loader, show_projected_labels = False):
fixed

2023-09-14 17:25 UTC, kirill-ivanov-a approved these changes

2023-09-18 08:14 UTC, merged